#![deny(clippy::unwrap_used, clippy::expect_used)]
#![cfg_attr(test, allow(clippy::unwrap_used, clippy::expect_used))]

//! Guest-side half of the `lycoris-abi-v1` WASM extension ABI (extension
//! system design, section 5.2): the support crate every Rust WASM extension
//! builds on.
//!
//! # ABI contract
//!
//! Core wasm, WASI disabled; the linker exposes only the `lycoris` host
//! module. The guest exports:
//!
//! - `memory` — the default linear memory;
//! - `lycoris_alloc(len: i32) -> i32` — guest allocator the host uses to place
//!   request bytes;
//! - `lycoris_invoke(method_ptr: i32, method_len: i32, payload_ptr: i32,
//!   payload_len: i32) -> i64` — the entry point; the return value packs the
//!   response buffer address as `(ptr << 32) | len` in guest memory.
//!
//! and imports from the `lycoris` module:
//!
//! - `log(level: i32, ptr: i32, len: i32)` — forwarded to `tracing` (0 = trace
//!   … 4 = error);
//! - `http(ptr: i32, len: i32) -> i64` — outbound HTTP, linked only when the
//!   manifest declares the `http` capability (llm-provider design, section 4);
//!   request and response are JSON documents, the response address packs like
//!   `lycoris_invoke`'s.
//!
//! Invocation payloads are JSON bytes end-to-end. The engine delivers the
//! resolved per-node settings by invoking `configure` at load time; a
//! failing configure fails the load (llm-provider design, section 5).
//!
//! # What this crate provides
//!
//! - [`export_extension!`]: generates the `lycoris_alloc` / `lycoris_invoke`
//!   exports, dispatching to a typed guest handler;
//! - [`host::log`] / [`host::http`]: safe wrappers over the host imports (stubs
//!   returning an error off `wasm32`, so guest crates compile and test on the
//!   host);
//! - [`shim`]: the (mostly pure) pieces the macro stitches together, exposed
//!   for host-side testing.
//!
//! # Panics and errors
//!
//! `wasm32-unknown-unknown` panics abort (there is no unwinding), so the
//! macro deliberately does **no** `catch_unwind`: handlers report failures
//! through `Result`, and a panic in guest code surfaces to the engine as a
//! trap, exactly like a handler error.

pub mod host;
pub mod shim;

/// Export the `lycoris-abi-v1` entry points for a guest extension.
///
/// `export_extension!(handler)` takes the path to the guest handler —
/// `fn(&str, serde_json::Value) -> Result<serde_json::Value, String>` — and
/// generates:
///
/// - `lycoris_alloc(len) -> ptr`: a bump allocator the host uses to place
///   request bytes (see [`shim::alloc`] for the growth semantics);
/// - `lycoris_invoke(method_ptr, method_len, payload_ptr, payload_len) -> i64`:
///   reads the method and the JSON payload out of linear memory, calls
///   `handler`, and returns the response buffer packed as `(ptr << 32) | len`.
///
/// Error semantics: an `Err` from the handler is logged through
/// [`host::log`] and then **traps** — the ABI has no typed error channel,
/// and a trap is what makes a failing `configure` fail the load. The engine
/// invokes `configure` at load time, so handlers must implement that method
/// (return `Ok` to accept or ignore the settings); rejecting it with `Err`
/// fails the load.
///
/// The generated exports exist only for `wasm32`; on other targets the macro
/// expands to nothing so the guest crate compiles for host-side tests.
///
/// # Example
///
/// ```
/// fn invoke(
///   method: &str, payload: serde_json::Value,
/// ) -> Result<serde_json::Value, String> {
///   match method {
///     "configure" => Ok(serde_json::json!({})),
///     "echo" => Ok(payload),
///     other => Err(format!("unknown method: {other}")),
///   }
/// }
///
/// lycoris_extguest::export_extension!(invoke);
/// ```
#[macro_export]
macro_rules! export_extension {
  ($handler:path) => {
    /// `lycoris-abi-v1` allocator export: hands the host a zeroed buffer of
    /// `len` bytes to fill (generated by
    /// [`export_extension!`](lycoris_extguest::export_extension)).
    #[cfg(target_arch = "wasm32")]
    #[allow(unsafe_code)] // Generated ABI shim; `no_mangle` is an unsafe attribute.
    #[unsafe(no_mangle)]
    pub extern "C" fn lycoris_alloc(len: i32) -> i32 {
      $crate::shim::alloc(len)
    }

    /// `lycoris-abi-v1` entry point export: dispatches to the handler passed
    /// to [`export_extension!`](lycoris_extguest::export_extension)
    /// and packs the response buffer as `(ptr << 32) | len`.
    #[cfg(target_arch = "wasm32")]
    #[allow(unsafe_code)] // Generated ABI shim: raw linear-memory IO + unsafe attribute.
    #[unsafe(no_mangle)]
    pub extern "C" fn lycoris_invoke(
      method_ptr: i32, method_len: i32, payload_ptr: i32, payload_len: i32,
    ) -> i64 {
      // SAFETY: the engine allocated both buffers through `lycoris_alloc`
      // and wrote exactly `len` bytes before this call, so they stay readable
      // for its whole duration.
      unsafe { $crate::shim::run(method_ptr, method_len, payload_ptr, payload_len, &$handler) }
    }
  };
}
