use std::{path::Path, time::Duration};

use ::time::OffsetDateTime;
use rcgen::{
  BasicConstraints, CertificateParams, DistinguishedName, DnType, IsCa, Issuer, KeyPair, SanType,
};
use tonic::transport::{Certificate, Identity};
use x509_parser::{extensions::GeneralName, prelude::*};

use crate::{TlsBundle, TlsError};

const CA_SUBJECT: &str = "lycoris-cluster-ca";
const NODE_CERT_VALIDITY: Duration = Duration::from_secs(365 * 24 * 60 * 60);
const CA_CERT_VALIDITY: Duration = Duration::from_secs(10 * 365 * 24 * 60 * 60);
const RENEWAL_THRESHOLD_DIVISOR: i64 = 3;
const NOT_BEFORE_SKEW: Duration = Duration::from_secs(60 * 60);

/// Parsed certificate information read from disk with x509-parser.
struct ParsedCert {
  not_before: OffsetDateTime,
  not_after: OffsetDateTime,
  sans: Vec<SanType>,
}

/// Ensure a usable TLS bundle exists at the configured paths.
///
/// - If the CA certificate does not exist, a new CA keypair and certificate is
///   generated and written to disk, along with a node certificate signed by
///   that CA.
/// - Otherwise the stored CA certificate is parsed and used as the issuer for
///   any newly signed node certificate. A CA or node certificate that is
///   expired (or has less than a third of its validity left) is renewed in
///   place; the CA keeps its key and subject, so existing trust anchors and
///   issued node certificates stay valid.
/// - The node certificate is re-issued when it is missing, unparsable, due for
///   renewal, or when its SANs do not cover the host of `advertise_addr` — the
///   name cluster peers verify this node against.
pub fn ensure_tls_bundle<P>(
  ca_cert_path: P, ca_key_path: P, cert_path: P, key_path: P, node_id: &str, advertise_addr: &str,
) -> Result<TlsBundle, TlsError>
where
  P: AsRef<Path>, {
  let ca_cert_path = ca_cert_path.as_ref();
  let ca_key_path = ca_key_path.as_ref();
  let cert_path = cert_path.as_ref();
  let key_path = key_path.as_ref();
  let host = advertise_host(advertise_addr)?;

  if !ca_cert_path.exists() {
    let (ca_cert_pem, ca_key_pem, cert_pem, key_pem) = generate_fresh_ca_and_node(node_id, &host)?;

    write_file(ca_cert_path, ca_cert_pem.clone())?;
    write_private_file(ca_key_path, &ca_key_pem)?;
    write_file(cert_path, cert_pem.clone())?;
    write_private_file(key_path, &key_pem)?;

    return bundle_from_strings(cert_pem, key_pem, ca_cert_pem);
  }

  let ca_key_pem = std::fs::read_to_string(ca_key_path)?;
  let ca_key = KeyPair::from_pem(&ca_key_pem)?;
  let ca_cert_pem = std::fs::read_to_string(ca_cert_path)?;

  let ca_parsed = parse_cert(&ca_cert_pem)?;
  let now = OffsetDateTime::now_utc();
  if needs_renewal(&ca_parsed, now) {
    tracing::info!(
      path = %ca_cert_path.display(),
      "cluster CA certificate is expired or close to expiry; renewing it with the same key"
    );
    // The CA is always generated by this code with known parameters
    // (CA_SUBJECT + IsCa::Ca(Unconstrained)), so reconstructing from
    // constants is faithful; the key never changes.
    let mut ca_params = ca_cert_params()?;
    ca_params.not_before = now - NOT_BEFORE_SKEW;
    ca_params.not_after = now + CA_CERT_VALIDITY;
    let renewed = ca_params.self_signed(&ca_key)?;
    write_file(ca_cert_path, renewed.pem())?;
  }

  // Build the issuer from the on-disk CA cert + key: rcgen's
  // `Issuer::from_ca_cert_pem` parses the exact subject DN and key usages,
  // so the issuer field of newly signed node certs matches what every peer
  // trusts byte-for-byte.
  let issuer = Issuer::from_ca_cert_pem(&std::fs::read_to_string(ca_cert_path)?, &ca_key)?;

  let mut reissue = !cert_path.exists() || !key_path.exists();
  if !reissue {
    match parse_cert(&std::fs::read_to_string(cert_path)?) {
      Ok(existing) if needs_renewal(&existing, now) => {
        tracing::info!(
          path = %cert_path.display(),
          "node certificate is expired or close to expiry; re-issuing"
        );
        reissue = true;
      }
      Ok(existing) if !san_covers(&existing.sans, &host) => {
        tracing::info!(
          path = %cert_path.display(),
          host,
          "node certificate does not cover the advertise address; re-issuing"
        );
        reissue = true;
      }
      Ok(_) => {}
      Err(error) => {
        tracing::warn!(
          path = %cert_path.display(),
          %error,
          "node certificate cannot be parsed; re-issuing"
        );
        reissue = true;
      }
    }
  }

  if reissue {
    let key = KeyPair::generate()?;
    let params = node_cert_params(node_id, &host, now)?;
    let cert = params.signed_by(&key, &issuer)?;
    write_file(cert_path, cert.pem())?;
    write_private_file(key_path, &key.serialize_pem())?;
  }

  let cert_pem = std::fs::read_to_string(cert_path)?;
  let key_pem = std::fs::read_to_string(key_path)?;
  let ca_cert_pem = std::fs::read_to_string(ca_cert_path)?;

  bundle_from_strings(cert_pem, key_pem, ca_cert_pem)
}

/// Extract the host part of an `https://host:port` advertise address.
fn advertise_host(address: &str) -> Result<String, TlsError> {
  let uri: tonic::codegen::http::Uri = address
    .parse()
    .map_err(|_| TlsError::InvalidAddress(address.to_string()))?;
  if uri.scheme_str() != Some("https") {
    return Err(TlsError::InvalidAddress(address.to_string()));
  }
  let host = uri
    .host()
    .ok_or_else(|| TlsError::InvalidAddress(address.to_string()))?;
  Ok(
    host
      .trim_start_matches('[')
      .trim_end_matches(']')
      .to_string(),
  )
}

fn generate_fresh_ca_and_node(
  node_id: &str, advertise_host: &str,
) -> Result<(String, String, String, String), TlsError> {
  let now = OffsetDateTime::now_utc();

  let ca_key = KeyPair::generate()?;
  let mut ca_params = ca_cert_params()?;
  ca_params.not_before = now - NOT_BEFORE_SKEW;
  ca_params.not_after = now + CA_CERT_VALIDITY;
  let ca_cert = ca_params.self_signed(&ca_key)?;

  let node_key = KeyPair::generate()?;
  let node_params = node_cert_params(node_id, advertise_host, now)?;
  let issuer = Issuer::from_params(&ca_params, &ca_key);
  let node_cert = node_params.signed_by(&node_key, &issuer)?;

  Ok((
    ca_cert.pem(),
    ca_key.serialize_pem(),
    node_cert.pem(),
    node_key.serialize_pem(),
  ))
}

/// Build CA certificate parameters from known constants.
///
/// The CA is always generated by this code; there is no external CA
/// provisioning path. The subject DN, SANs, and is-ca marker are therefore
/// identical across all renewals, and the CA key never changes.
fn ca_cert_params() -> Result<CertificateParams, TlsError> {
  let mut params = CertificateParams::new(vec![CA_SUBJECT.to_string()])?;
  params.is_ca = IsCa::Ca(BasicConstraints::Unconstrained);
  params.distinguished_name = common_name(CA_SUBJECT);
  Ok(params)
}

fn node_cert_params(
  node_id: &str, advertise_host: &str, now: OffsetDateTime,
) -> Result<CertificateParams, TlsError> {
  let mut names = vec!["localhost".to_string(), "127.0.0.1".to_string()];
  for name in [node_id, advertise_host] {
    if !names.iter().any(|existing| existing == name) {
      names.push(name.to_string());
    }
  }
  let mut params = CertificateParams::new(names)?;
  params.distinguished_name = common_name(node_id);
  params.not_before = now - NOT_BEFORE_SKEW;
  params.not_after = now + NODE_CERT_VALIDITY;
  Ok(params)
}

fn common_name(cn: &str) -> DistinguishedName {
  let mut name = DistinguishedName::new();
  name.push(DnType::CommonName, cn);
  name
}

/// True when the certificate is expired, has a broken validity window, or
/// has less than a third of its total validity left.
fn needs_renewal(parsed: &ParsedCert, now: OffsetDateTime) -> bool {
  let total = parsed.not_after.unix_timestamp() - parsed.not_before.unix_timestamp();
  let remaining = parsed.not_after.unix_timestamp() - now.unix_timestamp();
  total <= 0 || remaining <= 0 || remaining < total / RENEWAL_THRESHOLD_DIVISOR
}

fn san_covers(sans: &[SanType], name: &str) -> bool {
  sans.iter().any(|san| match san {
    SanType::DnsName(dns) => dns.as_str().eq_ignore_ascii_case(name),
    SanType::IpAddress(ip) => name
      .parse::<std::net::IpAddr>()
      .is_ok_and(|parsed| parsed == *ip),
    _ => false,
  })
}

// ---------------------------------------------------------------------------
// x509-parser helpers — read-only inspection of existing certs (validity +
// SANs). rcgen 0.14 removed `CertificateParams::from_ca_cert_pem`, so
// inspection uses x509-parser directly (it was already a transitive dep
// through rcgen's `x509-parser` feature).
// ---------------------------------------------------------------------------

/// Parse a PEM-encoded certificate just enough to read its validity window
/// and SANs.
fn parse_cert(pem_str: &str) -> Result<ParsedCert, TlsError> {
  let (pem, _) = Pem::read(std::io::Cursor::new(pem_str.as_bytes()))
    .map_err(|_e| TlsError::Generation(rcgen::Error::CouldNotParseCertificate))?;
  let (_, cert) = X509Certificate::from_der(&pem.contents)
    .map_err(|_e| TlsError::Generation(rcgen::Error::CouldNotParseCertificate))?;

  let validity = cert.validity();
  let not_before = asn1_to_offset(validity.not_before)?;
  let not_after = asn1_to_offset(validity.not_after)?;
  let sans = parse_sans(&cert);

  Ok(ParsedCert {
    not_before,
    not_after,
    sans,
  })
}

fn asn1_to_offset(time: ASN1Time) -> Result<OffsetDateTime, TlsError> {
  OffsetDateTime::from_unix_timestamp(time.timestamp())
    .map_err(|_e| TlsError::Generation(rcgen::Error::CouldNotParseCertificate))
}

/// OID 2.5.29.17: subjectAltName.
const OID_SAN_STR: &str = "2.5.29.17";

fn parse_sans(cert: &X509Certificate) -> Vec<SanType> {
  let mut sans = Vec::new();
  for ext in cert.extensions() {
    if ext.oid.to_id_string() != OID_SAN_STR {
      continue;
    }
    let result: Result<(_, x509_parser::extensions::SubjectAlternativeName<'_>), _> =
      FromDer::from_der(ext.value);
    if let Ok((_, parsed)) = result {
      for name in parsed.general_names {
        match name {
          GeneralName::DNSName(dns) => {
            if let Ok(ia5) = rcgen::string::Ia5String::try_from(dns) {
              sans.push(SanType::DnsName(ia5));
            }
          }
          GeneralName::IPAddress(bytes) => {
            let ip = match bytes.len() {
              4 => {
                let mut octets = [0u8; 4];
                octets.copy_from_slice(bytes);
                std::net::IpAddr::V4(std::net::Ipv4Addr::from(octets))
              }
              16 => {
                let mut octets = [0u8; 16];
                octets.copy_from_slice(bytes);
                std::net::IpAddr::V6(std::net::Ipv6Addr::from(octets))
              }
              _ => continue,
            };
            sans.push(SanType::IpAddress(ip));
          }
          _ => {}
        }
      }
    }
  }
  sans
}

fn write_file<P: AsRef<Path>>(path: P, content: String) -> Result<(), TlsError> {
  if let Some(parent) = path.as_ref().parent() {
    std::fs::create_dir_all(parent)?;
  }
  std::fs::write(path.as_ref(), content)?;
  Ok(())
}

fn write_private_file<P: AsRef<Path>>(path: P, content: &str) -> Result<(), TlsError> {
  lycoris_core::write_private_file(path, content.as_bytes())?;
  Ok(())
}

fn bundle_from_strings(
  cert_pem: String, key_pem: String, ca_pem: String,
) -> Result<TlsBundle, TlsError> {
  Ok(TlsBundle {
    identity: Identity::from_pem(cert_pem, key_pem),
    ca: Certificate::from_pem(ca_pem),
  })
}

#[cfg(test)]
mod tests {
  use tempfile::TempDir;

  use super::*;

  const TEST_ADDR: &str = "https://127.0.0.1:5001";

  fn cert_paths(
    dir: &TempDir,
  ) -> (
    std::path::PathBuf,
    std::path::PathBuf,
    std::path::PathBuf,
    std::path::PathBuf,
  ) {
    (
      dir.path().join("ca.crt"),
      dir.path().join("ca.key"),
      dir.path().join("node.crt"),
      dir.path().join("node.key"),
    )
  }

  fn parse_cert_for_test(pem_path: &Path) -> ParsedCert {
    parse_cert(&std::fs::read_to_string(pem_path).unwrap()).unwrap()
  }

  #[test]
  fn generates_ca_and_node_cert_when_missing() {
    let dir = TempDir::new().unwrap();
    let (ca_cert, ca_key, cert, key) = cert_paths(&dir);

    let bundle = ensure_tls_bundle(&ca_cert, &ca_key, &cert, &key, "test-node", TEST_ADDR).unwrap();
    assert!(ca_cert.exists());
    assert!(cert.exists());
    let _ = bundle;

    let node = parse_cert_for_test(&cert);
    assert!(san_covers(&node.sans, "127.0.0.1"));
    assert!(san_covers(&node.sans, "test-node"));
    assert!(!needs_renewal(&node, OffsetDateTime::now_utc()));
    let ca = parse_cert_for_test(&ca_cert);
    assert!(!needs_renewal(&ca, OffsetDateTime::now_utc()));
  }

  #[test]
  fn generates_node_cert_when_ca_exists() {
    let dir = TempDir::new().unwrap();
    let (ca_cert, ca_key, cert, key) = cert_paths(&dir);

    let _first = ensure_tls_bundle(&ca_cert, &ca_key, &cert, &key, "test-node", TEST_ADDR).unwrap();

    std::fs::remove_file(&cert).unwrap();
    std::fs::remove_file(&key).unwrap();

    let _second =
      ensure_tls_bundle(&ca_cert, &ca_key, &cert, &key, "test-node", TEST_ADDR).unwrap();
    assert!(cert.exists());
  }

  #[test]
  fn reissues_node_cert_when_advertise_host_changes() {
    let dir = TempDir::new().unwrap();
    let (ca_cert, ca_key, cert, key) = cert_paths(&dir);

    let _ = ensure_tls_bundle(&ca_cert, &ca_key, &cert, &key, "test-node", TEST_ADDR).unwrap();
    let before = std::fs::read_to_string(&cert).unwrap();

    let _ = ensure_tls_bundle(
      &ca_cert,
      &ca_key,
      &cert,
      &key,
      "test-node",
      "https://node.example:5001",
    )
    .unwrap();
    let after = std::fs::read_to_string(&cert).unwrap();

    assert_ne!(before, after);
    let node = parse_cert_for_test(&cert);
    assert!(san_covers(&node.sans, "node.example"));
    assert!(san_covers(&node.sans, "127.0.0.1"));
  }

  #[test]
  fn renews_expired_node_certificate() {
    let dir = TempDir::new().unwrap();
    let (ca_cert, ca_key, cert, key) = cert_paths(&dir);

    let _ = ensure_tls_bundle(&ca_cert, &ca_key, &cert, &key, "test-node", TEST_ADDR).unwrap();

    let ca_key_pair = KeyPair::from_pem(&std::fs::read_to_string(&ca_key).unwrap()).unwrap();
    let ca_cert_pem = std::fs::read_to_string(&ca_cert).unwrap();
    let issuer = Issuer::from_ca_cert_pem(&ca_cert_pem, &ca_key_pair).unwrap();
    let expired_key = KeyPair::generate().unwrap();
    let mut expired_params = CertificateParams::new(vec!["127.0.0.1".to_string()]).unwrap();
    let now = OffsetDateTime::now_utc();
    expired_params.not_before = now - Duration::from_secs(3600);
    expired_params.not_after = now - Duration::from_secs(60);
    let expired = expired_params.signed_by(&expired_key, &issuer).unwrap();
    std::fs::write(&cert, expired.pem()).unwrap();
    std::fs::write(&key, expired_key.serialize_pem()).unwrap();

    let _ = ensure_tls_bundle(&ca_cert, &ca_key, &cert, &key, "test-node", TEST_ADDR).unwrap();

    let node = parse_cert_for_test(&cert);
    assert!(!needs_renewal(&node, OffsetDateTime::now_utc()));
  }

  #[test]
  fn renews_expiring_ca_with_same_key() {
    let dir = TempDir::new().unwrap();
    let (ca_cert, ca_key, cert, key) = cert_paths(&dir);

    let _ = ensure_tls_bundle(&ca_cert, &ca_key, &cert, &key, "test-node", TEST_ADDR).unwrap();
    let node_before = std::fs::read_to_string(&cert).unwrap();

    let ca_key_pair = KeyPair::from_pem(&std::fs::read_to_string(&ca_key).unwrap()).unwrap();
    let mut expired_ca = ca_cert_params().unwrap();
    let now = OffsetDateTime::now_utc();
    expired_ca.not_before = now - Duration::from_secs(3600);
    expired_ca.not_after = now - Duration::from_secs(60);
    std::fs::write(
      &ca_cert,
      expired_ca.self_signed(&ca_key_pair).unwrap().pem(),
    )
    .unwrap();

    let _ = ensure_tls_bundle(&ca_cert, &ca_key, &cert, &key, "test-node", TEST_ADDR).unwrap();

    let ca = parse_cert_for_test(&ca_cert);
    assert!(!needs_renewal(&ca, OffsetDateTime::now_utc()));
    assert_eq!(node_before, std::fs::read_to_string(&cert).unwrap());
  }

  #[test]
  fn extracts_advertise_host() {
    assert_eq!(advertise_host("https://node-0:5001").unwrap(), "node-0");
    assert_eq!(advertise_host("https://10.0.0.5:5001").unwrap(), "10.0.0.5");
    assert_eq!(advertise_host("https://[::1]:5001").unwrap(), "::1");
    assert!(advertise_host("node-0:5001").is_err());
  }
}
